sudo: required
services:
  - docker
install: true
stages:
  - build
  - name: push-image
    if: type != pull_request


jobs:
  include:
    - stage: build
      script:
        - docker run --rm -v $PWD:/usr/local/src -w /usr/local/src node:8-alpine sh -c 'npm i -g npm && npm i --no-optional && npm run build'
    - stage: push-image
      if: tag IS present
      script:
      - docker run -e NPM_TOKEN=$NPM_TOKEN--rm -v $PWD:/usr/local/src -w /usr/local/src node:8-alpine sh -c 'npm i -g npm && npm i --no-optional && npm run build && npm publish'

